"""add_plans_table

Revision ID: 0ce20b32c727
Revises: b3783b2e0db8
Create Date: 2026-08-08 21:30:07.339283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0ce20b32c727'
down_revision: Union[str, Sequence[str], None] = 'b3783b2e0db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adcode', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index('idx_user_adcode', 'plans', ['user_id', 'adcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('idx_user_adcode', table_name='plans')
    op.drop_table('plans')
