"""init all tables

Revision ID: 6b8c089ded3c
Revises: 
Create Date: 2026-08-08 20:19:41.002955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8c089ded3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('budgets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adcode', sa.String(length=20), nullable=False),
    sa.Column('category', sa.SmallInteger(), nullable=False),
    sa.Column('custom_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_index('idx_user_city', 'budgets', ['user_id', 'adcode'], unique=False)
    op.create_table('light_cities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adcode', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_light_cities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_light_cities')),
    sa.UniqueConstraint('user_id', 'adcode', name='uk_user_adcode')
    )
    op.create_table('trips',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adcode', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_table('bills',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.SmallInteger(), nullable=False),
    sa.Column('custom_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_bills_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills'))
    )
    op.create_index('idx_trip', 'bills', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trip', table_name='bills')
    op.drop_table('bills')
    op.drop_table('trips')
    op.drop_table('light_cities')
    op.drop_index('idx_user_city', table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('users')
    # ### end Alembic commands ###
